name:                hs-chat
version:             0.1.0.0
github:              "cassiofariasmachado/hs-chat"
license:             BSD3
author:              "Cassio Farias Machado"
maintainer:          "cassiofariasmachado@yahoo.com"
copyright:           "2019 Cassio Farias Machado"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cassiofariasmachado/hs-chat#readme>

dependencies:
- base >= 4.7 && < 5
- network >= 3.1.0.0
- bytestring
- directory

library:
  source-dirs: src

executables:
  hs-chat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-chat

tests:
  hs-chat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-chat
